stages:
  prepare_data:
    cmd: python src/data_preparation.py
    deps:
    - data/Dataset.xlsx
    - src/data_preparation.py
    outs:
    - data/cleaned/housing_claimants_clean.csv
    - data/cleaned/housing_spend_clean.csv
    - data/cleaned/imd_data_clean.csv
    - data/cleaned/population_estimates_clean.csv
  integrate_data:
    cmd: python src/data_integration.py
    deps:
    - data/cleaned/housing_claimants_clean.csv
    - data/cleaned/housing_spend_clean.csv
    - data/cleaned/imd_data_clean.csv
    - data/cleaned/population_estimates_clean.csv
    - src/data_integration.py
    outs:
    - data/merged/merged_data.csv
  explore_data:
    cmd: python src/exploratory_analysis.py
    deps:
    - data/merged/merged_data.csv
    - src/exploratory_analysis.py
    outs:
    - data/explore/quality_summary.csv
    - data/explore/usable_columns.csv
  model_selection:
    cmd: python src/model_selection.py
    deps:
    - data/merged/merged_data.csv
    - src/model_selection.py
    params:
    - model_selection.n_clusters
    outs:
    - data/model/clustered_data.csv
    - data/model/final_selection.csv
  results:
    cmd: python src/results.py
    deps:
    - data/model/clustered_data.csv
    - data/model/final_selection.csv
    - src/results.py
    outs:
    - data/results/briefing.xlsx
    - plots/bar_avg_imd.png
    - plots/cluster_scatter.png
    - plots/spend_by_cluster.png
    - plots/spend_quartiles_by_cluster.png
